version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:${REDIS_PORT}"
    container_name: LinkZipperRedis
  postgres:
    image: postgres:latest
    ports:
      - "5432:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: LinkZipperDB